version: '3.0'

networks:
  health_net:
    external: false

services:
  healthbot_core:
    build: ./
    container_name: healthbot_core
    restart: always
    networks:
      - health_net
    volumes:
      - ./:/app/
    command:
      - "run"
      - "--enable-api"
      - "--cors"
      - "*"
      - "--credential"
      - "credentials.yml"
      - "--endpoints"
      - "endpoints.yml"
      - "--port"
      - "5005"
    links:
      - healthbot_actions
    ports:
      - "5005:5005"
    expose: [5005]
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M


  healthbot_actions:
    build: ./actions
    container_name: healthbot_actions
    restart: always
    networks:
      - health_net
    volumes:
      - ./actions:/app/actions
    expose: [5055]
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: ".25"
          memory: 250M
